ICONS = {
    0: "https://i.imgur.com/jNJ1BBl.png",
    1: "https://i.imgur.com/deTjm7V.png",
    2: "https://i.imgur.com/zx5KbBO.png",
    3: "https://i.imgur.com/RTCvQDV.png",
    4: "https://i.imgur.com/SN55IoP.png",
    5: "https://i.imgur.com/DmfZeRP.png",
    6: "https://i.imgur.com/QOuIDW4.png",
    7: "https://i.imgur.com/ry1KwLe.png",
    8: "https://i.imgur.com/64eQSbG.png",
    9: "https://i.imgur.com/fOmokW9.png",
    10: "https://i.imgur.com/e84XmHl.png",
    11: "https://i.imgur.com/f68iB99.png",
    12: "https://i.imgur.com/iQGr0yz.png",
    13: "https://i.imgur.com/DelhMBP.png",
    14: "https://i.imgur.com/5fYa6cM.png",
    15: "https://i.imgur.com/7c4dBTz.png",
    16: "https://i.imgur.com/cOFgDW5.png",
    17: "https://i.imgur.com/27k46er.png",
    18: "https://i.imgur.com/0nSeDwK.png",
    19: "https://i.imgur.com/p8J2gyx.png",
    20: "https://i.imgur.com/h02BrKN.png",
    21: "https://i.imgur.com/h02BrKN.png",
}

NAMES = {
    0: "Unranked",
    1: "Copper IV",
    2: "Copper III",
    3: "Copper II",
    4: "Copper I",
    5: "Bronve IV",
    6: "Bronze III",
    7: "Bronze II",
    8: "Bronze I",
    9: "Silver IV",
    10: "Silver III",
    11: "Silver II",
    12: "Silver I",
    13: "Gold IV",
    14: "Gold III",
    15: "Gold II",
    16: "Gold I",
    17: "Platinum III",
    18: "Platinum II",
    19: "Platinum I",
    20: "Diamond",
    21: "Diamond I",
}
